import os, json, base64, time
import requests
from typing import Dict

class GitHubPublisher:
    """DNA auto-push repo ke GitHub."""
    
    def __init__(self):
        # Baca token dari environment ATAU file .env
        self.token = os.getenv("GITHUB_TOKEN")
        if not self.token:
            env_path = os.path.expanduser("~/AI/.env")
            if os.path.exists(env_path):
                with open(env_path) as f:
                    for line in f:
                        if line.startswith('GITHUB_TOKEN='):
                            self.token = line.strip().split('=', 1)[1].strip()
                            os.environ['GITHUB_TOKEN'] = self.token
                            break
        if not self.token:
            self.token = ""  # Fallback
        self.api = "https://api.github.com"
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def create_repo(self, dna, name: str) -> str:
        """Bikin repo baru."""
        r = requests.post(f"{self.api}/user/repos", headers=self.headers,
            json={"name": name, "auto_init": True})
        if r.status_code == 201:
            dna.log_action(f"📦 Repo created: {name}")
            return r.json()["html_url"]
        return ""
    
    def push_file(self, dna, repo: str, path: str, content: str, msg="Auto-commit by DNA") -> bool:
        """Push file ke repo. Update jika sudah ada."""
        url = f"{self.api}/repos/{repo}/contents/{path}"
        # Cek apakah file sudah ada
        existing = requests.get(url, headers=self.headers)
        payload = {"message": msg, "content": base64.b64encode(content.encode()).decode()}
        if existing.status_code == 200:
            payload["sha"] = existing.json().get("sha")
        r = requests.put(url, headers=self.headers, json=payload)
        ok = r.status_code in (200, 201)
        if ok: dna.log_action(f"📄 Pushed: {path}")
        return ok
    
    def execute(self, dna, repo_name: str = "", files: Dict[str, str] = None) -> Dict:
        """Entry point. Bikin repo + push files."""
        user = requests.get(f"{self.api}/user", headers=self.headers).json().get("login", "qnd-dna")
        repo = f"{user}/{repo_name or f'dna-project-{int(time.time())}'}"
        url = self.create_repo(dna, repo_name or f"dna-project-{int(time.time())}")
        if not url: return {"success": False}
        
        if not files:
            files = {"index.html": "<h1>DNA Project</h1><p>Auto-generated by QND Colony</p>",
                     "README.md": f"# {repo_name}\nBuilt by {dna.dna_id}"}
        
        for path, content in files.items():
            self.push_file(dna, repo, path, content)
        
        return {"success": True, "repo_url": url, "files": list(files.keys())}

github_pub = GitHubPublisher()
